# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VKGeeKBrainsTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VKGeeKBrainsTest
  pod 'SwiftKeychainWrapper'
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'Kingfisher'
  pod 'RealmSwift'
  pod 'Firebase/Analytics'
  pod 'FirebaseDatabase'
  pod 'Firebase/Auth'



end
